apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-logs-describe
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["watch", "list", "get"]